title: "Henry Stephenson"
author: "Henry Stephenson"
description: "McGill Bioengineering, Minors of Applied AI & Finance"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "aboutme.html", title: "About Me"}
  - {file: "cv.html", title: "CV"}
  - {file: "posts.html", title: "Posts"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:stephensonhenry.03@gmail.com"}
  - {title: Mail, icon: envelope, url: "mailto:edward.stephenson@mail.mcgill.ca"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/henry-steph"}
  - {title: Google Scholar, icon: fa-google, url: "https://scholar.google.ca/citations?user=JU_sQNkAAAAJ&hl=en&oi=ao"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
